config/routes.rb
Rails.application.routes.draw do

  resources :categories

  get '/assign_categories' => 'assign_category#new'
  post '/assign_categories' => 'assign_category#create'

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :comments

  resources :answers

  resources :questions

  root to: 'home#index'

  get 'admin' => 'admin#index'

  post 'vote' => 'vote#vote'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

    user ||= User.new
    if user.admin?
        can :manage, :all
    else
        can :read, :all
    end

  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
	has_many :comments
	belongs_to :question
end

app/models/assign_category.rb
class AssignCategory
  ValidationError = Class.new(StandardError)

  include ActiveModel::Model
  include Virtus.model

  attribute :name, String
  attribute :question, Integer

  validates :name, presence: true

  def persisted?
    false
  end

  def validate!
    raise ValidationError, errors unless valid?
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many :votes
	has_many :answers
	belongs_to :category

	attr_reader :name
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  # rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # has_and_belongs_to_many :roles, :join_table => :users_roles

  Roles = [ :admin, :default ]

  def is? requested_role
    self.role == requested_role.to_s
  end

  def self.admin_role
    return Roles[0]
  end

  def self.default_role
    return Roles[1]
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :user
	belongs_to :question
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_filter :is_admin

	def index
	end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]
  before_filter :is_admin, except: [:create]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        question = Question.find(params[:question][:id]) 
        question.answers << @answer
        format.html { redirect_to question, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@questions = Question.all
		@question = Question.new
	end
end

app/controllers/vote_controller.rb
class VoteController < ApplicationController

	def vote
		question_id = params[:question][:id]
		user_id = current_user.id
		vote = Vote.where(["question_id = :q", { q: question_id }]).where(["user_id = :u", { u: user_id }]).take
		50.times{p vote}
		respond_to do |format|
			if vote.nil?
				@vote = Vote.new
				@vote.question = Question.find question_id
				@vote.user = User.find user_id
				@vote.save
			end
			votes = Vote.where(["question_id = :q", { q: question_id }]).count
			format.json { render :json => { status: true, votes: votes } }
		end
	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assign_category_helper.rb
module AssignCategoryHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/vote_helper.rb
module VoteHelper
end

app/views/home/index.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="col-md-offset-2">
    <h1>Questions and Answers</h1>
  </div>

  <%= form_for(@question, html: { class: "form-horizontal" }) do |f| %>
    <% if @question.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>
        <ul>
        <% @question.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :description, "Ask a question", class: "col-sm-2 control-label" %><br>
      <div class="col-sm-10">
      	<%= f.text_area :description, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
    	<div class="col-sm-offset-2 col-sm-10">
      	<%= f.submit class: "btn btn-default" %>
      </div>
    </div>
  <% end %>

  <ul class="list-groups">
  <% @questions.each do |question| %>
  	<li class="list-group-item bottom-padding">
      <%= link_to question.description, question_path(question) %>
      <%= form_for(question, :url => url_for(:controller => 'vote', :action => 'vote'), method: :post, remote: true, html: { class: 'form-inline pull-right', name: 'upvote-form' }) do |f| %>
        <% if (Vote.where(["question_id = :q", { q: question.id }]).where(["user_id = :u", { u: current_user.id }]).take.nil?) %>
          <%= f.submit '+1', class: "btn btn-info", name: "upvote" %>
        <% else %>
          <%= f.submit '+1', class: "btn btn-info disabled", name: "upvote" %>
        <% end %>
        <span class="badge" id="vote-count-<%= question.id %>"><%= question.votes.count %></span>
        <%= f.hidden_field :id, :value => question.id %>
      <% end %>
    </li>
  <% end %>
  </ul>
</div>